### ISSUE TITLE
The Transpiler uses code

### ISSUE THREAD

**Issue by abhijit-hota** [littledivy/nocode-transpiler#1]
Imo, Elixir is not the best choice for writing a transpiler for nocode.

I think [Whitespace](https://esolangs.org/wiki/Whitespace) could be a preferred option.

Anyway, thank you so much for making this!

**Comment by littledivy** [comment]
https://github.com/littledivy/nocode-transpiler/blob/48a2fecf42cd40146cc5c551fc7d186c120d60ce/Transpiler.exs#L5 The transpiler is written in nocode. It is embeddable. Elixir is just leveraging nocode. It is advised to uninstall elixir after use.
